---
kind: pipeline
type: kubernetes
name: default

trigger:
  ref:
    include:
      - 'refs/tags/v*'
      - 'refs/heads/main'
      - 'refs/heads/DOP-3787'

steps:
  - name: publish-staging
    image: plugins/ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: 795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - push

  - name: publish-prod
    image: plugins/ecr
    settings:
      create_repository: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: 795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/${DRONE_REPO_NAME}
      tags:
        - git-${DRONE_COMMIT_SHA:0:7}
        - latest
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
    when:
      event:
        - tag

  - name: deploy-staging
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.12.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: docs-search-transport
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=docs-search-transport.docs.staging.corp.mongodb.com
      values_files: ['environments/all.yml', 'environments/staging.yml']
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
    when:
      event:
        - push

  - name: deploy-prod
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.12.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: docs
      release: docs-search-transport
      values: image.tag=git-${DRONE_COMMIT_SHA:0:7},image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/docs/${DRONE_REPO_NAME},ingress.enabled=true,ingress.hosts[0]=docs-search-transport.docs.prod.corp.mongodb.com
      values_files: ['environments/all.yml', 'environments/prod.yml']
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
    when:
      event:
        - tag
