ingress:
  enabled: true
  hosts:
    - docs-search-transport.docs.prod.corp.mongodb.com

env:
  MANIFEST_URI: 's3://docs-search-indexes-test/search-indexes/prd/'
  ATLAS_DATABASE: 'search'
  ATLAS_ADMIN_PUB_KEY: 'cbkapemu'

resources:
  limits:
    memory: 1300Mi
  requests:
    memory: 1100Mi
