ingress:
  enabled: true
  hosts:
    - docs-search-transport.docs.prod.corp.mongodb.com

env:
  MANIFEST_URI: 's3://docs-search-indexes-test/search-indexes/prd/'
  ATLAS_DATABASE: 'search'
  ATLAS_ADMIN_PUB_KEY: 'cbkapemu'
  POOL_DB: 'pool'
  S3_BUCKET: docs-search-indexes-test
  S3_PATH: search-indexes/prd

resources:
  limits:
    memory: 1800Mi
  requests:
    memory: 1600Mi
