ingress:
  enabled: true
  hosts:
    - docs-search-transport.docs.staging.corp.mongodb.com

env:
  MANIFEST_URI: 's3://docs-search-indexes-test/search-indexes/preprd/'
  ATLAS_DATABASE: 'search-staging'
  ATLAS_ADMIN_PUB_KEY: 'dgrhrxpv'
  POOL_DB: 'pool_test'

resources:
  limits:
    memory: 800Mi
  requests:
    memory: 600Mi
