# This workflow will compile the tsc and commit the build directory
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js build

on:
  push:
    branches: 
      - main
      - DOP-3596

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
      - name: tsc
        uses: icrawl/action-tsc@v1
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          # TODO: change above the main